account_master/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

# app_name = 'account_master'

urlpatterns = [
    # Обработчики для логина/выход из системы
    # path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # Обработчики по смене пароля
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # бработчики для восстановления пароля
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # Обработчики для регистрации
    path('register/', views.register, name='register'),
    path('edit_master/', views.edit_master, name='edit_master'),

]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ad/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'ad'

urlpatterns = [
    path('', views.promotion_list, name='promotion_list'),
    path('<slug:category_slug>/', views.promotion_list, name='promotion_list_by_category'),
    path('<slug:subcategory_slug>/', views.promotion_list, name='promotion_list_by_subcategory'),
    path('<int:id>/<slug:slug>/', views.promotion_detail, name='promotion_detail'),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gsp_testing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account_master/', include('account_master.urls')),
    # path('ad/', include('ad.urls', namespace='ad')),
    path('promotions/', include('reclame.urls', namespace='promotions')),
    path('', include('job.urls', namespace='job')),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'job'

urlpatterns = [
    # Обработчики для регистрации заказа в системе
    path('register_job/', views.register_job, name='register_job'),
    # Обработчики для вывода заказов с категориями
    path('', views.offer_list, name='offer_list'),
    path('<slug:category_slug>/', views.offer_list, name='offer_list_by_category'),
    # Обработчики для вывода заказа с подробной информацией
    path('<int:id>/<slug:slug>/', views.offer_detail, name='offer_detail'),

]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_master/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings


class Master(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь')
    slug = models.SlugField(blank=True, null=True, max_length=200, unique=True, verbose_name='User')
    middle_name = models.CharField(blank=True, null=True, default=None, max_length=200,
                                   verbose_name='Отчество мастера')
    phone = models.CharField(max_length=64, blank=True, null=True, default=None, verbose_name='Номер тел. мастера')
    date_of_birth = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    photo = models.ImageField(upload_to='masters/%Y/%m/%d/', blank=True, verbose_name='Фотография мастера')
    description = models.TextField(max_length=512, blank=True, verbose_name='Описание мастера')
    available = models.BooleanField(default=False, verbose_name='Актуальность мастера')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Мастер'
        verbose_name_plural = 'Мастера'

    def __str__(self):
        return 'Профиль пользователя {}'.format(self.user.username)

ad/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название категории')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Nazvanie_kategorii')
    is_active = models.BooleanField(default=True, null=True, blank=True, verbose_name='Активность категории')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория рекламы'
        verbose_name_plural = 'Категории реклам'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('ad:promotion_list_by_category', args=[self.slug])


class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE,
                                 verbose_name='Категория рекламы')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название подкатегории')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Nazvanie_podkategorii')
    is_active = models.BooleanField(default=True, null=True, blank=True, verbose_name='Активность категории')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Подкатегория рекламы'
        verbose_name_plural = 'Подкатегории реклам'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('ad:promotion_list_by_subcategory', args=[self.slug])


class Promotion(models.Model):
    category = models.ManyToManyField(Category, related_name='promotions', blank=True,
                                 verbose_name='Категория рекламы')
    subcategory = models.ForeignKey(SubCategory, related_name='promotions', on_delete=models.CASCADE,
                                    verbose_name='Податегория рекламы')
    # subcategory_2 = models.ManyToManyField(Category, blank=True, null=True, verbose_name='Категория рекламы_2')
    name = models.CharField(blank=True, null=True, default=None, max_length=200, verbose_name='Название рекламодателя')
    slug = models.SlugField(max_length=200, db_index=True, verbose_name='Nazvanie_reklamodatelya')
    country = models.CharField(blank=True, null=True, default='Россия', max_length=200, verbose_name='Страна')
    region = models.CharField(blank=True, null=True, default='Курская область', max_length=200, verbose_name='Регион')
    town = models.CharField(blank=True, null=True, default='Курск', max_length=200, verbose_name='Город')
    address = models.TextField(max_length=512, blank=True, verbose_name='Адрес')
    site = models.URLField(max_length=1024, blank=True, default=None, null=None, verbose_name='Сайт')
    phone = models.CharField(max_length=128, blank=True, null=True, default=None, verbose_name='Номер тел.')
    email = models.EmailField(max_length=128, blank=True, null=True, default=None, verbose_name='Емейл')
    photo = models.ImageField(upload_to='promotions_photos/%Y/%m/%d', blank=True, verbose_name='Фото')
    logotype = models.ImageField(upload_to='promotions_logotypes/%Y/%m/%d', blank=True, verbose_name='Логотип')
    description = models.TextField(max_length=2048, blank=True, verbose_name='Описание деятельности')
    is_active = models.BooleanField(default=False, verbose_name='Активность рекламы')
    paid = models.BooleanField(default=False, verbose_name='Оплачен показ рекламы?')
    schedule_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Пон - Пт)')
    schedule_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Пон - Пт)')
    weekend_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Суббота)')
    weekend_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Суббота)')
    weekend2_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Воскресенье)')
    weekend2_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Воскресенье)')
    dinner_time_start = models.TimeField(blank=True, null=True, verbose_name='Обеденный перерыв (начало)')
    dinner_time_end = models.TimeField(blank=True, null=True, verbose_name='Обеденный перерыв (конец)')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    @property
    def Категории(self):
        return "\n".join([p.name for p in self.category.all()])

    class Meta:
        ordering = ('-created', 'name')
        index_together = (('id', 'slug'),)
        verbose_name = 'Рекламирование'
        verbose_name_plural = 'Рекламирование'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('ad:promotion_detail', args=[self.id, self.slug])


class PromotionDetails(models.Model):
    promotion = models.ForeignKey(Promotion, blank=True, null=True, default=None, on_delete=models.CASCADE, verbose_name='Место под рекламу (детали)')
    is_main = models.BooleanField(default=False, blank=True, null=True, verbose_name='Главный офис')
    is_not_main = models.BooleanField(default=True, blank=True, null=True, verbose_name='Дополнительный офис')
    is_active = models.BooleanField(default=True, blank=True, null=True, verbose_name='Активный?')
    schedule_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Пон - Пт)')
    schedule_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Пон - Пт)')
    weekend_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Суббота)')
    weekend_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Суббота)')
    weekend2_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Воскресенье)')
    weekend2_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Воскресенье)')
    dinner_time_start = models.TimeField(blank=True, null=True, verbose_name='Обеденный перерыв (начало)')
    dinner_time_end = models.TimeField(blank=True, null=True, verbose_name='Обеденный перерыв (конец)')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Подробная информация к рекламодателям'
        verbose_name_plural = 'Подробная информация к рекламодателям'

account_master/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Master


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class MasterEditForm(forms.ModelForm):
    class Meta:
        model = Master
        fields = ('date_of_birth', 'photo', 'middle_name', 'phone', 'description')

job/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Offer, MPTTModel, Category
from mptt.forms import *


class OfferRegistrationForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    middle_name = forms.CharField(required=False)
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=True)
    price = forms.DecimalField(required=True)
    start_time = forms.DateField(required=False)
    end_time = forms.DateField(required=False)
    description = forms.Textarea()
    # category = TreeNodeChoiceField(queryset=Category.objects.filter(is_active=True))
    image = forms.ImageField(required=False)

    class Meta:
        model = Offer
        fields = ('first_name', 'last_name', 'middle_name', 'phone', 'email', 'name', 'image', 'description', 'price', 'start_time', 'end_time')
        exclude = ['created', 'updated', 'category']

account_master/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib import messages
from .forms import LoginForm, UserRegistrationForm, UserEditForm, MasterEditForm
from django.contrib.auth.decorators import login_required
from .models import Master


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account_master/login.html', {'form': form})


@login_required
def dashboard(request):
    return render(request, 'account_master/dashboard.html', {'section': 'dashboard'})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Создаем нового юзера, но в БАЗЕ он НЕ СОХРАНЕН! ПОКА ЧТО!
            new_user = user_form.save(commit=False)
            # Зададим юзеру пароль для его аккаунта
            new_user.set_password(user_form.cleaned_data['password'])
            # Сохраним юзера в БАЗЕ
            new_user.save()
            Master.objects.create(user=new_user)
            return render(request, 'account_master/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account_master/register.html', {'user_form': user_form})


@login_required
def edit_master(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        master_form = MasterEditForm(instance=request.user.master,
                                     data=request.POST,
                                     files=request.FILES)
        if user_form.is_valid() and master_form.is_valid():
            user_form.save()
            master_form.save()
        #     messages.success(request, 'Profile updated successfully')
        # else:
        #     messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        master_form = MasterEditForm(instance=request.user.master)
    return render(request, 'account_master/edit_master.html', {
        'user_form': user_form,
        'master_form': master_form
    })

templates/account_master/dashboard.html
{% extends "base.html" %}
{% block title %}Личный кабинет{% endblock %}
{% block content %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="../../static/css/bootstrap.css">
<link rel="stylesheet" href="../../static/vendors/linericon/style.css">
<link rel="stylesheet" href="../../static/css/font-awesome.min.css">
<link rel="stylesheet" href="../../static/vendors/owl-carousel/owl.carousel.min.css">
<link rel="stylesheet" href="../../static/vendors/lightbox/simpleLightbox.css">
<link rel="stylesheet" href="../../static/vendors/nice-select/css/nice-select.css">
<link rel="stylesheet" href="../../static/vendors/animate-css/animate.css">
<link rel="stylesheet" href="../../static/vendors/jquery-ui/jquery-ui.css">
<!-- main css -->
<link rel="stylesheet" href="../../static/css/style.css">
<link rel="stylesheet" href="../../static/css/responsive.css">

<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>Добро пожаловать в систему!</h2>
                <div class="page_link">
                    <a href="{% url 'job:offer_list' %}">Заказы</a>
                    <a href="{% url 'logout' %}">Выйти из системы</a>
                </div>
                <div class="page_link">
                    <a href={% url 'password_change' %}>Сменить пароль</a>
                    <a>Смена пароля</a>
                </div>
                <div class="page_link">
                    <a href={% url 'edit_master' %}>Изменить свой профиль</a>
                    <a>Профиль</a>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="../../static/js/jquery-3.2.1.min.js"></script>
<script src="../../static/js/popper.js"></script>
<script src="../../static/js/bootstrap.min.js"></script>
<script src="../../static/js/stellar.js"></script>
<script src="../../static/vendors/lightbox/simpleLightbox.min.js"></script>
<script src="../../static/vendors/nice-select/js/jquery.nice-select.min.js"></script>
<script src="../../static/vendors/isotope/imagesloaded.pkgd.min.js"></script>
<script src="../../static/vendors/isotope/isotope-min.js"></script>
<script src="../../static/vendors/owl-carousel/owl.carousel.min.js"></script>
<script src="../../static/js/jquery.ajaxchimp.min.js"></script>
<script src="../../static/vendors/counter-up/jquery.waypoints.min.js"></script>
<script src="../../static/vendors/flipclock/timer.js"></script>
<script src="../../static/vendors/counter-up/jquery.counterup.js"></script>
<script src="../../static/js/mail-script.js"></script>
<script src="../../static/js/theme.js"></script>

{% endblock %}

templates/account_master/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Логин/Регистрация
{% endblock %}

{% block content %}

<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>Логин/Регистрация</h2>
                <div class="page_link">
                    <a href="index.html">Назад</a>
                    <a href="login.html">Логин</a>
                </div>
            </div>
        </div>
    </div>
</section>

<!--================Login Box Area =================-->
<section class="login_box_area p_120">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="login_box_img">
                    <img class="img-fluid" src="../../static/img/login.jpg" alt="">
                    <div class="hover">
                        <h4>Не зарегистрированный мастер?</h4>
                        <p>Прежде чем брать заказы, Вам необходимо зарегистрироваться в нашей системе</p>
                        <a class="main_btn" href="{% url 'register' %}">Создать новый аккаунт</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="login_form_inner">
                    <h3>Поля для входа в систему</h3>
                    <form class="row login_form" action="." method="post" id="contactForm" novalidate="novalidate">
                        <div class="col-md-12 form-group">
                            <input required type="text" class="form-control" id="name" name="{{ form.username.name }}" placeholder="Имя пользователя">
                        </div>
                        <div class="col-md-12 form-group">
                            <input required type="password" class="form-control" id="id_password" name="{{ form.password.name }}" placeholder="Пароль">
                        </div>
                        <div class="col-md-12 form-group">
                            <div class="creat_account">
                                <input type="checkbox" id="f-option2" name="selector">
                                <label for="f-option2">Оставаться в системе</label>
                            </div>
                        </div>
                        {% csrf_token %}
                        <div class="col-md-12 form-group">
                            <button type="submit" value="submit" class="btn submit_btn">Вход</button>
                            <a href="#">Забыли пароль?</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/account_master/register.html
{% extends "base.html" %}
{% block title %}Регистрация | ГСП{% endblock %}
{% block content %}

<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>Регистрация</h2>
                <div class="page_link">
                    <a href={% url 'job:offer_list' %}>Назад</a>
                    <a href='#'>Логин</a>
                </div>
            </div>
        </div>
    </div>
</section>

<!--================Login Box Area =================-->
<section class="login_box_area p_120">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="login_box_img">
                    <img class="img-fluid" src="../../static/img/login.jpg" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="login_form_inner">
                    {% if user_form.errors %}
                    <p class="alert alert-danger">Аккаунт с таким именем пользователя уже существует!</p>
                    <p>Пожалуйста, попробуйте ввести другие данные</p>
                    {% else %}
                    <p>Пожалуйста, используйте форму ниже для входа в систему</p>
                    {% endif %}
                    <h3>Поля для регистрации в системе:</h3>
                    <form class="row login_form" action="." method="post" id="contactForm" novalidate="novalidate">
                        <div class="col-md-12 form-group">
                            <input type="text" class="form-control" required id="id_username" name="{{ user_form.username.name }}" placeholder="Имя пользователя">
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="text" class="form-control" id="id_first_name" name="{{ user_form.first_name.name }}" placeholder="Ваше настоящее имя">
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="email" class="form-control" id="id_email" name="{{ user_form.email.name }}" placeholder="Ваш электронный адрес">
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="password" class="form-control" required id="id_password" name="{{ user_form.password.name }}" placeholder="Пароль">
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="password" class="form-control" required id="id_password2" name="{{ user_form.password2.name }}" placeholder="Повторите введенный пароль">
                        </div>
                        <div class="col-md-12 form-group">
                            <div class="creat_account">
                                <input type="checkbox" id="f-option2" name="selector">
                                <label for="f-option2">Оставаться в системе</label>
                            </div>
                        </div>
                        {% csrf_token %}
                        <div class="col-md-12 form-group">
                            <button type="submit" value="submit" class="btn submit_btn">Создать аккаунт</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Login Box Area =================-->

{% endblock %}

templates/account_master/register_done.html
{% extends "base.html" %}

{% block title %}Аккаунт создан | ГСП{% endblock %}
{% block content %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href='../../static/css/bootstrap.css'>
<link rel="stylesheet" href="../../static/vendors/linericon/style.css">
<link rel="stylesheet" href="../../static/css/font-awesome.min.css">
<link rel="stylesheet" href="../../static/vendors/owl-carousel/owl.carousel.min.css">
<link rel="stylesheet" href="../../static/vendors/lightbox/simpleLightbox.css">
<link rel="stylesheet" href="../../static/vendors/nice-select/css/nice-select.css">
<link rel="stylesheet" href="../../static/vendors/animate-css/animate.css">
<link rel="stylesheet" href="../../static/vendors/jquery-ui/jquery-ui.css">
<!-- main css -->
<link rel="stylesheet" href="../../static/css/style.css">
<link rel="stylesheet" href="../../static/css/responsive.css">

<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>Аккаунт создан</h2>
                <div class="page_link">
                    <a href={% url 'job:offer_list' %}>Назад</a>
                    <a>Ваш аккаунт создан</a>
                </div>
            </div>
        </div>
    </div>
</section>

<!--================Order Details Area =================-->
<section class="order_details p_120">
    <div class="container">
        <h3 class="title_confirmation">Все прошло успешно, {{ new_user.first_name }}! Теперь Вы можете
<a href="{% url "login" %}">войти в свою учетную запись</a></h3>
    </div>
</section>
<!--================End Order Details Area =================-->

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="../../static/js/jquery-3.2.1.min.js"></script>
<script src="../../static/js/popper.js"></script>
<script src="../../static/js/bootstrap.min.js"></script>
<script src="../../static/js/stellar.js"></script>
<script src="../../static/vendors/lightbox/simpleLightbox.min.js"></script>
<script src="../../static/vendors/nice-select/js/jquery.nice-select.min.js"></script>
<script src="../../static/vendors/isotope/imagesloaded.pkgd.min.js"></script>
<script src="../../static/vendors/isotope/isotope-min.js"></script>
<script src="../../static/vendors/owl-carousel/owl.carousel.min.js"></script>
<script src="../../static/js/jquery.ajaxchimp.min.js"></script>
<script src="../../static/vendors/counter-up/jquery.waypoints.min.js"></script>
<script src="../../static/vendors/flipclock/timer.js"></script>
<script src="../../static/vendors/counter-up/jquery.counterup.js"></script>
<script src="../../static/js/mail-script.js"></script>
<script src="../../static/js/theme.js"></script>

{% endblock %}