ad/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'ad'

urlpatterns = [
    path('', views.promotion_list, name='promotion_list'),
    path('<slug:category_slug>/', views.promotion_list, name='promotion_list_by_category'),
    path('<slug:subcategory_slug>/', views.promotion_list, name='promotion_list_by_subcategory'),
    path('<int:id>/<slug:slug>/', views.promotion_detail, name='promotion_detail'),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gsp_testing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account_master/', include('account_master.urls')),
    # path('ad/', include('ad.urls', namespace='ad')),
    path('promotions/', include('reclame.urls', namespace='promotions')),
    path('', include('job.urls', namespace='job')),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'job'

urlpatterns = [
    # Обработчики для регистрации заказа в системе
    path('register_job/', views.register_job, name='register_job'),
    # Обработчики для вывода заказов с категориями
    path('', views.offer_list, name='offer_list'),
    path('<slug:category_slug>/', views.offer_list, name='offer_list_by_category'),
    # Обработчики для вывода заказа с подробной информацией
    path('<int:id>/<slug:slug>/', views.offer_detail, name='offer_detail'),

]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ad/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название категории')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Nazvanie_kategorii')
    is_active = models.BooleanField(default=True, null=True, blank=True, verbose_name='Активность категории')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория рекламы'
        verbose_name_plural = 'Категории реклам'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('ad:promotion_list_by_category', args=[self.slug])


class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE,
                                 verbose_name='Категория рекламы')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название подкатегории')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Nazvanie_podkategorii')
    is_active = models.BooleanField(default=True, null=True, blank=True, verbose_name='Активность категории')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Подкатегория рекламы'
        verbose_name_plural = 'Подкатегории реклам'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('ad:promotion_list_by_subcategory', args=[self.slug])


class Promotion(models.Model):
    category = models.ManyToManyField(Category, related_name='promotions', blank=True,
                                 verbose_name='Категория рекламы')
    subcategory = models.ForeignKey(SubCategory, related_name='promotions', on_delete=models.CASCADE,
                                    verbose_name='Податегория рекламы')
    # subcategory_2 = models.ManyToManyField(Category, blank=True, null=True, verbose_name='Категория рекламы_2')
    name = models.CharField(blank=True, null=True, default=None, max_length=200, verbose_name='Название рекламодателя')
    slug = models.SlugField(max_length=200, db_index=True, verbose_name='Nazvanie_reklamodatelya')
    country = models.CharField(blank=True, null=True, default='Россия', max_length=200, verbose_name='Страна')
    region = models.CharField(blank=True, null=True, default='Курская область', max_length=200, verbose_name='Регион')
    town = models.CharField(blank=True, null=True, default='Курск', max_length=200, verbose_name='Город')
    address = models.TextField(max_length=512, blank=True, verbose_name='Адрес')
    site = models.URLField(max_length=1024, blank=True, default=None, null=None, verbose_name='Сайт')
    phone = models.CharField(max_length=128, blank=True, null=True, default=None, verbose_name='Номер тел.')
    email = models.EmailField(max_length=128, blank=True, null=True, default=None, verbose_name='Емейл')
    photo = models.ImageField(upload_to='promotions_photos/%Y/%m/%d', blank=True, verbose_name='Фото')
    logotype = models.ImageField(upload_to='promotions_logotypes/%Y/%m/%d', blank=True, verbose_name='Логотип')
    description = models.TextField(max_length=2048, blank=True, verbose_name='Описание деятельности')
    is_active = models.BooleanField(default=False, verbose_name='Активность рекламы')
    paid = models.BooleanField(default=False, verbose_name='Оплачен показ рекламы?')
    schedule_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Пон - Пт)')
    schedule_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Пон - Пт)')
    weekend_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Суббота)')
    weekend_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Суббота)')
    weekend2_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Воскресенье)')
    weekend2_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Воскресенье)')
    dinner_time_start = models.TimeField(blank=True, null=True, verbose_name='Обеденный перерыв (начало)')
    dinner_time_end = models.TimeField(blank=True, null=True, verbose_name='Обеденный перерыв (конец)')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    @property
    def Категории(self):
        return "\n".join([p.name for p in self.category.all()])

    class Meta:
        ordering = ('-created', 'name')
        index_together = (('id', 'slug'),)
        verbose_name = 'Рекламирование'
        verbose_name_plural = 'Рекламирование'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('ad:promotion_detail', args=[self.id, self.slug])


class PromotionDetails(models.Model):
    promotion = models.ForeignKey(Promotion, blank=True, null=True, default=None, on_delete=models.CASCADE, verbose_name='Место под рекламу (детали)')
    is_main = models.BooleanField(default=False, blank=True, null=True, verbose_name='Главный офис')
    is_not_main = models.BooleanField(default=True, blank=True, null=True, verbose_name='Дополнительный офис')
    is_active = models.BooleanField(default=True, blank=True, null=True, verbose_name='Активный?')
    schedule_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Пон - Пт)')
    schedule_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Пон - Пт)')
    weekend_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Суббота)')
    weekend_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Суббота)')
    weekend2_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Воскресенье)')
    weekend2_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Воскресенье)')
    dinner_time_start = models.TimeField(blank=True, null=True, verbose_name='Обеденный перерыв (начало)')
    dinner_time_end = models.TimeField(blank=True, null=True, verbose_name='Обеденный перерыв (конец)')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Подробная информация к рекламодателям'
        verbose_name_plural = 'Подробная информация к рекламодателям'

job/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField


class Category(MPTTModel):
    name = models.CharField(max_length=200, db_index=True, unique=True, verbose_name='Подкатегория')
    slug = models.SlugField(max_length=200, null=True, blank=True, unique=True, verbose_name='Nazvanie_kategorii')
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children',
                            verbose_name='Категория')
    is_active = models.BooleanField(default=True, verbose_name='Активность категории')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    class MPTTMeta:
        order_insertion_by = ['name']
        verbose_name = 'Категория -> Подкатегория'
        verbose_name_plural = 'Категории -> Подкатегории'

    class Meta:
        verbose_name = 'Категория -> Подкатегория'
        verbose_name_plural = 'Категории -> Подкатегории'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('job:offer_list_by_category', args=[self.slug])


class Offer(models.Model):
    category = TreeManyToManyField(Category, related_name='offers', blank=True, verbose_name='Категория работ')
    first_name = models.CharField(blank=True, null=True, default=None, max_length=200, verbose_name='Имя заказчика')
    last_name = models.CharField(blank=True, null=True, default=None, max_length=200, verbose_name='Фамилия заказчика')
    middle_name = models.CharField(blank=True, null=True, default=None, max_length=200, verbose_name='Отчество заказчика')
    phone = models.CharField(max_length=64, blank=True, null=True, default=None, verbose_name='Номер тел.')
    email = models.EmailField(max_length=128, blank=True, null=True, default=None, verbose_name='Емейл')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Наименование работ')
    slug = models.SlugField(max_length=200, db_index=True, verbose_name='Слаг')
    image = models.ImageField(upload_to='offers/%Y/%m/%d', blank=True, verbose_name='Фото')
    description = models.TextField(max_length=512, blank=True, verbose_name='Описание работ')
    price = models.DecimalField(blank=True, null=True, default=None, max_digits=10, decimal_places=0,
                                verbose_name='Цена работы')
    start_time = models.DateField(null=True, blank=True, default=None, verbose_name='Дата начала работ')
    end_time = models.DateField(null=True, blank=True, default=None, verbose_name='Дата окончания работ')
    available = models.BooleanField(default=False, verbose_name='Актуальность заказа')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    @property
    def Категории(self):
        return "\n".join([p.name for p in self.category.all()])

    class Meta:
        ordering = ('-created', 'name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Предложение о работе'
        verbose_name_plural = 'Предложения о работе'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('job:offer_detail', args=[self.id, self.slug])

job/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Offer, MPTTModel, Category
from mptt.forms import *


class OfferRegistrationForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    middle_name = forms.CharField(required=False)
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=True)
    price = forms.DecimalField(required=True)
    start_time = forms.DateField(required=False)
    end_time = forms.DateField(required=False)
    description = forms.Textarea()
    # category = TreeNodeChoiceField(queryset=Category.objects.filter(is_active=True))
    image = forms.ImageField(required=False)

    class Meta:
        model = Offer
        fields = ('first_name', 'last_name', 'middle_name', 'phone', 'email', 'name', 'image', 'description', 'price', 'start_time', 'end_time')
        exclude = ['created', 'updated', 'category']

job/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Offer
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import OfferRegistrationForm
from utils.emails import SendingEmail


# from utils.emails import SendingEmail


def offer_list(request, category_slug=None):
    category = None
    categories = Category.objects.filter(is_active=True)
    object_list = Offer.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        object_list = object_list.filter(category=category)
    paginator = Paginator(object_list, 8)
    page = request.GET.get('page')
    try:
        offers = paginator.page(page)
    except PageNotAnInteger:
        offers = paginator.page(1)
    except EmptyPage:
        offers = paginator.page(paginator.num_pages)

    return render(request, 'job/list.html', {'category': category,
                                             'categories': categories,
                                             'page': page,
                                             'offers': offers})


def offer_detail(request, id, slug):
    offer = get_object_or_404(Offer, id=id, slug=slug, available=True)
    return render(request, 'job/detail.html', {'offer': offer})


def register_job(request):
    if request.method == 'POST':
        offer_form = OfferRegistrationForm(request.POST, request.FILES)
        if offer_form.is_valid():
            print(request.POST)
            print(offer_form.cleaned_data)
            print('yes')
            data = offer_form.cleaned_data
            first_name = data.get('first_name')
            last_name = data.get('last_name')
            middle_name = data.get('middle_name')
            name = data.get('name')
            description = data.get('description')
            email = data.get('email')
            phone = data.get('phone')
            category = data.get('category')
            image = data.get('image')
            price = data.get('price')
            start_time = data.get('start_time')
            end_time = data.get('end_time')

            # new_offer = Offer.objects.create(first_name=first_name, last_name=last_name, middle_name=middle_name,
            #                                  email=email, phone=phone, name=name, start_time=start_time,
            #                                  end_time=end_time, image=image, description=description, price=price)

            new_offer = offer_form.save(commit=False)
            # Сохраним заказ в БАЗЕ
            new_offer.save()

            # Offer.objects.create(all(new_offer))

            email = SendingEmail()
            email.sending_email(type_id=1, new_offer=new_offer)
            email.sending_email(type_id=2, email=new_offer.email, new_offer=new_offer)
            return render(request, 'job/register_job_done.html', {'new_offer': new_offer})
    else:
        offer_form = OfferRegistrationForm()
    return render(request, 'job/register_job.html', {'offer_form': offer_form})

templates/job/detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}{{ offer.name }}{% endblock %}
{% block content %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../../static/css/bootstrap.css">
    <link rel="stylesheet" href="../../static/vendors/linericon/style.css">
    <link rel="stylesheet" href="../../static/css/font-awesome.min.css">
    <link rel="stylesheet" href="../../static/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="../../static/vendors/lightbox/simpleLightbox.css">
    <link rel="stylesheet" href="../../static/vendors/nice-select/css/nice-select.css">
    <link rel="stylesheet" href="../../static/vendors/animate-css/animate.css">
    <link rel="stylesheet" href="../../static/vendors/jquery-ui/jquery-ui.css">
    <!-- main css -->
    <link rel="stylesheet" href="../../static/css/style.css">
    <link rel="stylesheet" href="../../static/css/responsive.css">

<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>{% if offer %}{{ offer.name }}{% else %}Работа{% endif %}</h2>
                <div class="page_link">
                    <a href={% url 'job:offer_list' %}>Домой</a>
                    <a href="#">{% if offer %}{{ offer.name }}{% else %}Работа{% endif %}</a>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="product_image_area">
    <div class="container">
        <div class="row s_product_inner">
            <div class="col-lg-6">
                <div class="s_product_img">
                    <img class="img-fluid" src="{% if offer.image %}{{ offer.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
{#							<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">#}
{#								<ol class="carousel-indicators">#}
{#									<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active">#}
{#										<img src="img/product/single-product/s-product-s-2.jpg" alt="">#}
{#									</li>#}
{#									<li data-target="#carouselExampleIndicators" data-slide-to="1">#}
{#										<img src="img/product/single-product/s-product-s-3.jpg" alt="">#}
{#									</li>#}
{#									<li data-target="#carouselExampleIndicators" data-slide-to="2">#}
{#										<img src="img/product/single-product/s-product-s-4.jpg" alt="">#}
{#									</li>#}
{#								</ol>#}
{#								<div class="carousel-inner">#}
{#									<div class="carousel-item active">#}
{#										<img class="d-block w-100" src="img/product/single-product/s-product-1.jpg" alt="First slide">#}
{#									</div>#}
{#									<div class="carousel-item">#}
{#										<img class="d-block w-100" src="img/product/single-product/s-product-1.jpg" alt="Second slide">#}
{#									</div>#}
{#									<div class="carousel-item">#}
{#										<img class="d-block w-100" src="img/product/single-product/s-product-1.jpg" alt="Third slide">#}
{#									</div>#}
{#								</div>#}
{#							</div>#}
                </div>
            </div>
            <div class="col-lg-5 offset-lg-1">
                <div class="s_product_text">
                    <h3>{{ offer.name }}</h3>
                    <h2>{{ offer.price }} руб. </h2>
                    <ul class="list">
{#                        <li><a class="active" href="{{ offer.category.name.get_absolute_url }}"><span>Категория</span> : {{ offer.Категории.name }}</a></li>#}
                        {% if offer.start_time and offer.end_time %}
                        <i class="lnr lnr-calendar-full"> Начать с: {{ offer.start_time }} </i><br>
                        <i class="lnr lnr-calendar-full"> Закончить по: {{ offer.end_time }} </i>
                        {% else %}
                        <i class="lnr lnr-calendar-full"> Начать в любое время </i>
                        {% endif %}
                    </ul>
                    <p>{{offer.description}}</p>
                    {% if request.user.is_authenticated %}
                        <div class="card_area">
                            <a class="main_btn" href="#">Откликнуться</a>
                        </div>
                        {% else %}
                        <div class="card_area">
                            <a class="active" href="{% url 'login' %}">Войдите</a> или <a class="" href="{% url 'login' %}">Зарегистрируйтесь</a>, чтобы откликаться на заказы
                        </div>
                    {% endif %}
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="../../static/js/jquery-3.2.1.min.js"></script>
<script src="../../static/js/popper.js"></script>
<script src="../../static/js/bootstrap.min.js"></script>
<script src="../../static/js/stellar.js"></script>
<script src="../../static/vendors/lightbox/simpleLightbox.min.js"></script>
<script src="../../static/vendors/nice-select/js/jquery.nice-select.min.js"></script>
<script src="../../static/vendors/isotope/imagesloaded.pkgd.min.js"></script>
<script src="../../static/vendors/isotope/isotope-min.js"></script>
<script src="../../static/vendors/owl-carousel/owl.carousel.min.js"></script>
<script src="../../static/js/jquery.ajaxchimp.min.js"></script>
<script src="../../static/vendors/counter-up/jquery.waypoints.min.js"></script>
<script src="../../static/vendors/flipclock/timer.js"></script>
<script src="../../static/vendors/counter-up/jquery.counterup.js"></script>
<script src="../../static/js/mail-script.js"></script>
<script src="../../static/js/theme.js"></script>

{% endblock %}

templates/job/register_job.html
{% extends "base.html" %}
{% load static %}

{% block title %}Добавить заказ, тендер | ГСП{% endblock %}

{% block content %}

<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>Опубликуйте свой заказ или тендер</h2>
                <div class="page_link">
                    <a href={% url 'job:offer_list' %}>Назад</a>
                    <a href='#'>Добавить заказ</a>
                </div>
            </div>
        </div>
    </div>
</section>

<!--================Login Box Area =================-->
<section class="login_box_area p_120">
    <div class="container">
        <div class="row">
{#            <div class="col-lg-6">#}
{#                <div class="login_box_img">#}
{#                    <img class="img-fluid" src="{% static 'img/login.jpg' %}" alt="">#}
{#                </div>#}
{#            </div>#}
            <div class="col-lg-12">
                <div class="job_form_inner">
                    {% if offer_form.errors %}
                        <p class="alert alert-danger">Введите данные для формы правильно</p>
                        <p>Пожалуйста, попробуйте ввести другие данные</p>
                            {% else %}
                        <p>Пожалуйста, используйте форму ниже для добавления заказа:</p>
                        <p>* отмечены поля для обязательного заполнения</p>
                    {% endif %}
                    <h3>Поля для публикации Вашего заказа в системе:</h3>
                    <form class="row login_form" action="{% url 'job:register_job' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
{#                        <div class="col-md-12 input-group-icon mt-10">#}
{#                            <div class="form-select valid">#}
{#                                <span class="current">Выберите категорию работ *:</span>#}
{#                                {{ offer_form.category }}#}
{#                            </div>#}
{#                        </div>#}
{#                        <br>#}
                        <div class="col-md-4 form-group">
                            <input class="form-control-offer valid" name="{{ offer_form.first_name.name }}" value="{{ request.POST.name }}" id="first_name" required type="text" onfocus="this.placeholder = 'Это поле обязательно'" onblur="this.placeholder = 'Введите Ваше имя'" placeholder="Ваше имя *">
                        </div>
                        <div class="col-md-4 form-group">
                            <input class="form-control-offer valid" name="{{ offer_form.last_name.name }}" value="{{ request.POST.name }}" id="last_name" required type="text" onfocus="this.placeholder = 'Это поле обязательно'" onblur="this.placeholder = 'Введите Вашу фамилию'" placeholder="Ваша фамилия *">
                        </div>
                        <div class="col-md-4 form-group">
                            <input class="form-control-offer" name="{{ offer_form.middle_name.name }}" value="{{ request.POST.name }}" id="middle_name" required type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Введите Ваше отчество'" placeholder="Ваше отчество">
                        </div>
                        <div class="col-md-6 form-group">
                            <input class="form-control-offer valid" name="{{ offer_form.phone.name }}" value="{{ request.POST.name }}" id="phone" required type="number" onfocus="this.placeholder = 'Это поле обязательно'" onblur="this.placeholder = 'Введите Ваш номер телефона'" placeholder="Ваш номер телефона *">
                        </div>
                        <div class="col-md-6 form-group">
                            <input class="form-control-offer valid" name="{{ offer_form.email.name }}" value="{{ request.POST.name }}" id="email" required type="email" onfocus="this.placeholder = 'Это поле обязательно'" onblur="this.placeholder = 'Введите Ваш email'" placeholder="Ваша электронная почта *">
                        </div>
                        <div class="col-md-12 form-group">
                            <input class="form-control-offer valid" name="{{ offer_form.name.name }}" value="{{ request.POST.name }}" id="name" required type="text" onfocus="this.placeholder = 'Это поле обязательно'" onblur="this.placeholder = 'Ваш заказ'" placeholder="Что нужно сделать? *">
                        </div>
                        <div class="col-md-12 form-group">
                            <textarea class="form-control-offer valid" name="{{ offer_form.description.name }}" id="description" cols="30" rows="9" required type="text" onfocus="this.placeholder = 'Это поле обязательно'" onblur="this.placeholder = 'Объём и виды работ, пожелания и требования'" placeholder="Укажите объём и виды работ, опишите пожелания и требования *"></textarea>
                        </div>
                        <div class="col-md-6 form-group">
                            <span class="current">Когда начать работы?</span>
                            <input class="form-control-offer" name="{{ offer_form.start_time.name }}" value="{{ request.POST.name }}" id="start_time" required type="date" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Дата начала работ'" placeholder="Когда начать работы?">
                        </div>
                        <div class="col-md-6 form-group">
                            <span class="current">Когда закончить работы?</span>
                            <input class="form-control-offer" name="{{ offer_form.end_time.name }}" value="{{ request.POST.name }}" id="end_time" required type="date" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Дата окончания работ'" placeholder="Когда закончить работы?">
                        </div>
                        <div class="col-md-12 form-group">
                            <input class="form-control-offer valid" name="{{ offer_form.price.name }}" value="{{ request.POST.name }}" id="price" required type="number" onfocus="this.placeholder = 'Это поле обязательно'" onblur="this.placeholder = 'Введите сумму, которую Вы готовы заплатить за работу'" placeholder="Укажите бюджет *">
                        </div>
                        <div class="col-md-12 form-group">
                            <span class="current">Приложите фотографию объекта</span>
{#                            <input class="form-control-offer" type="file" id="image" name="{{ offer_form.image }} {{ offer_form.image_file }}">#}
                            <input type="file" class="form-control-offer" accept="image/*" id="id_photo" name="{{ offer_form.image.name }}" placeholder="Фотография">
                        </div>
                        <div class="col-md-12 form-group">
                            <button type="submit" value="submit" class="btn submit_btn">Опубликовать заказ</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Login Box Area =================-->

{% endblock %}