ad/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'ad'

urlpatterns = [
    path('', views.promotion_list, name='promotion_list'),
    path('<slug:category_slug>/', views.promotion_list, name='promotion_list_by_category'),
    path('<slug:subcategory_slug>/', views.promotion_list, name='promotion_list_by_subcategory'),
    path('<int:id>/<slug:slug>/', views.promotion_detail, name='promotion_detail'),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gsp_testing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account_master/', include('account_master.urls')),
    # path('ad/', include('ad.urls', namespace='ad')),
    path('promotions/', include('reclame.urls', namespace='promotions')),
    path('', include('job.urls', namespace='job')),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reclame/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'reclame'

urlpatterns = [
    path('', views.promotion_list, name='promotion_list'),
    path('<slug:category_slug>/', views.promotion_list, name='promotion_list_by_category'),
    # path('<slug:subcategory_slug>/', views.show_genres, name='promotion_list_by_subcategory'),
    path('<int:id>/<slug:slug>/', views.promotion_detail, name='promotion_detail'),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reclame/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField


class Category(MPTTModel):
    name = models.CharField(max_length=50, unique=True, verbose_name='Подкатегория')
    slug = models.SlugField(max_length=200, null=True, blank=True, unique=True, verbose_name='Nazvanie_kategorii')
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children',
                            verbose_name='Категория')
    is_active = models.BooleanField(default=True, verbose_name='Активность категории')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    class MPTTMeta:
        order_insertion_by = ['name']
        verbose_name = 'Тест мптт'
        verbose_name_plural = 'Тест мптт'

    class Meta:
        verbose_name = 'Категория -> Подкатегория'
        verbose_name_plural = 'Категории -> Подкатегории'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('reclame:promotion_list_by_category', args=[self.slug])


class Promotion(models.Model):
    category = TreeManyToManyField(Category, blank=True, symmetrical=False, related_name='promotions', verbose_name='Категория')
    # category = TreeForeignKey(Genre, blank=True, null=True, default=None, on_delete=models.CASCADE, related_name='promotions', verbose_name='Категория')
    name = models.CharField(blank=True, null=True, default=None, max_length=200, verbose_name='Название рекламодателя')
    slug = models.SlugField(null=True, blank=True, max_length=200, db_index=True,
                            verbose_name='Nazvanie_reklamodatelya')
    country = models.CharField(blank=True, null=True, default='Россия', max_length=200, verbose_name='Страна')
    region = models.CharField(blank=True, null=True, default='Курская область', max_length=200, verbose_name='Регион')
    town = models.CharField(blank=True, null=True, default='Курск', max_length=200, verbose_name='Город')
    site = models.URLField(max_length=1024, blank=True, default=None, null=None, verbose_name='Сайт')
    email = models.EmailField(max_length=128, blank=True, null=True, default=None, verbose_name='Емейл')
    photo = models.ImageField(upload_to='promotions_test_photos/%Y/%m/%d', blank=True, verbose_name='Фото')
    logotype = models.ImageField(upload_to='promotions_test_logotypes/%Y/%m/%d', blank=True, verbose_name='Логотип')
    description = models.TextField(max_length=512, blank=True, verbose_name='Описание деятельности')
    is_active = models.BooleanField(default=False, verbose_name='Активность рекламы')
    paid = models.BooleanField(default=False, verbose_name='Оплачен показ рекламы?')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    class Meta:
        ordering = ('-created', 'name')
        index_together = (('id', 'slug'),)
        verbose_name = 'Место под рекламу'
        verbose_name_plural = 'Места под рекламу'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('reclame:promotion_detail', args=[self.id, self.slug])


class PromotionDetails(models.Model):
    promotion = models.ForeignKey(Promotion, blank=True, null=True, default=None, on_delete=models.CASCADE,
                                  verbose_name='Место под рекламу (детали)')
    is_main = models.BooleanField(default=False, blank=True, null=True, verbose_name='Гл. офис?')
    is_not_main = models.BooleanField(default=True, blank=True, null=True, verbose_name='Доп. офис')
    is_active = models.BooleanField(default=True, blank=True, null=True, verbose_name='Активный?')
    address = models.CharField(max_length=1024, blank=True, verbose_name='Адрес')
    phone = models.CharField(max_length=128, blank=True, null=True, default=None, verbose_name='Номер тел.')
    schedule_start = models.TimeField(blank=True, null=True, verbose_name='Н. раб. дня (Пон - Пт)')
    schedule_end = models.TimeField(blank=True, null=True, verbose_name='К. раб. дня (Пон - Пт)')
    weekend_start = models.TimeField(blank=True, null=True, verbose_name='Н. раб. дня (Суббота)')
    weekend_end = models.TimeField(blank=True, null=True, verbose_name='К. раб. дня (Суббота)')
    weekend2_start = models.TimeField(blank=True, null=True, verbose_name='Н. раб. дня (Воскресенье)')
    weekend2_end = models.TimeField(blank=True, null=True, verbose_name='К. раб. дня (Воскресенье)')
    dinner_time_start = models.TimeField(blank=True, null=True, verbose_name='Обед. пер-в (н.)')
    dinner_time_end = models.TimeField(blank=True, null=True, verbose_name='Обед. пер-в (к.)')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Подробная информация к рекламодателю'
        verbose_name_plural = 'Подробная информация к рекламодателям'

reclame/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Promotion, PromotionDetails
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Это обработчик странички с рекламой. Тут пагинация. По дефолту поставил 50 итемов.
# Да, и Алина сука.
def promotion_list(request, category_slug=None):
    category = None
    categories = Category.objects.filter(is_active=True)
    object_list = Promotion.objects.filter(is_active=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        object_list = object_list.filter(category=category)
    paginator = Paginator(object_list, 50)
    page = request.GET.get('page')
    try:
        promotions = paginator.page(page)
    except PageNotAnInteger:
        promotions = paginator.page(1)
    except EmptyPage:
        promotions = paginator.page(paginator.num_pages)
    return render(request, "reclame/list.html", {'category': category,
                                                 'categories': categories,
                                                 'promotions': promotions})


def promotion_detail(request, id, slug):
    promotion = get_object_or_404(Promotion, id=id, slug=slug, is_active=True)
    promotion_details = get_object_or_404(PromotionDetails, id=id, is_active=True)
    promotion_details_main = PromotionDetails.objects.filter(is_main=True, is_active=True)
    promotion_details_not_main = PromotionDetails.objects.filter(is_not_main=True, is_active=True)
    return render(request, 'reclame/detail.html', {'promotion': promotion,
                                                   'promotion_details': promotion_details,
                                                   'promotion_details_main': promotion_details_main,
                                                   'promotion_details_not_main': promotion_details_not_main,
                                                   })

templates/reclame/detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}{{ promotion.name }}{% endblock %}
{% block content %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../../../static/css/bootstrap.css">
    <link rel="stylesheet" href="../../../static/vendors/linericon/style.css">
    <link rel="stylesheet" href="../../../static/css/font-awesome.min.css">
    <link rel="stylesheet" href="../../../static/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="../../../static/vendors/lightbox/simpleLightbox.css">
    <link rel="stylesheet" href="../../../static/vendors/nice-select/css/nice-select.css">
    <link rel="stylesheet" href="../../../static/vendors/animate-css/animate.css">
    <link rel="stylesheet" href="../../../static/vendors/jquery-ui/jquery-ui.css">
    <!-- main css -->
    <link rel="stylesheet" href="../../../static/css/style.css">
    <link rel="stylesheet" href="../../../static/css/responsive.css">

<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>{% if promotion %}{{ promotion.name }}{% else %}Работа{% endif %}</h2>
                <div class="page_link">
                    <a href={% url 'reclame:promotion_list' %}>Домой</a>
                    <a href="#">{% if promotion %}{{ promotion.name }}{% else %}Работа{% endif %}</a>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="product_image_area">
    <div class="container">
        <div class="row s_product_inner">
            <div class="col-lg-6">
                <div class="s_product_img">
                    <img class="img-fluid" src="{% if promotion.photo %}{{ promotion.photo.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
{#							<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">#}
{#								<ol class="carousel-indicators">#}
{#									<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active">#}
{#										<img src="img/product/single-product/s-product-s-2.jpg" alt="">#}
{#									</li>#}
{#									<li data-target="#carouselExampleIndicators" data-slide-to="1">#}
{#										<img src="img/product/single-product/s-product-s-3.jpg" alt="">#}
{#									</li>#}
{#									<li data-target="#carouselExampleIndicators" data-slide-to="2">#}
{#										<img src="img/product/single-product/s-product-s-4.jpg" alt="">#}
{#									</li>#}
{#								</ol>#}
{#								<div class="carousel-inner">#}
{#									<div class="carousel-item active">#}
{#										<img class="d-block w-100" src="img/product/single-product/s-product-1.jpg" alt="First slide">#}
{#									</div>#}
{#									<div class="carousel-item">#}
{#										<img class="d-block w-100" src="img/product/single-product/s-product-1.jpg" alt="Second slide">#}
{#									</div>#}
{#									<div class="carousel-item">#}
{#										<img class="d-block w-100" src="img/product/single-product/s-product-1.jpg" alt="Third slide">#}
{#									</div>#}
{#								</div>#}
{#							</div>#}
                </div>
            </div>
            <div class="col-lg-5 offset-lg-1">
                <div class="s_product_text">
                    <h3>{{ promotion.name }}</h3>
                    <ul class="list">
{#                        <li><a class="active" href="{{ promotion.category.get_absolute_url }}">{{ promotion.category }}</a></li>#}
{#                        <li><a><i class="lnr lnr-home"></i> Адрес: {{ promotion.country }}, {{ promotion.region }}, г. {{ promotion.town }}, {{ promotion_details_main.address }}</a>#}
{#                        </li>#}
                        {% if promotion.email %}
                            <li><a><i class="lnr lnr-envelope"></i> E-mail: {{ promotion.email }}</a></li>
                        {% endif %}
                    <hr>
                        {% for m in promotion.promotiondetails_set.all %}
                            {% if m.schedule_start and m.schedule_end %}
                                <li><a><i class="lnr lnr-home"></i> Адрес: {{ promotion.country }}, {{ promotion.region }}, г. {{ promotion.town }}, {{ m.address }}</a>
                                <li><a><i class="lnr lnr-clock"></i> Часы работы (Пн - Пт): {{ m.schedule_start|time:'H:i' }} - {{ m.schedule_end|time:'H:i' }}</a></li>
                                {% else %}
                                    <li><a><i class="lnr lnr-calendar-full"></i> Часы работы: круглосуточно </a></li>
                            {% endif %}
                            {% if m.weekend_start and m.weekend_end %}
                                <li><a><i class="lnr lnr-clock"></i> Часы работы (Суббота): {{ m.weekend_start|time:'H:i' }} - {{ m.weekend_end|time:'H:i' }}</a></li>
                                {% else %}
                                    <li><a><i class="lnr lnr-calendar-full"></i> Суббота - выходной день </a></li>
                            {% endif %}
                            {% if m.weekend2_start and m.weekend2_end %}
                                <li><a><i class="lnr lnr-clock"></i> Часы работы (Воскресенье): {{ m.weekend2_start|time:'H:i' }} - {{ m.weekend2_end|time:'H:i' }}</a></li>
                                {% else %}
                                    <li><a><i class="lnr lnr-calendar-full"></i> Воскресенье - выходной день </a></li>
                            {% endif %}
                            {% if m.dinner_time_start and m.dinner_time_end %}
                                <li><a><i class="lnr lnr-dinner"></i> Обеденный перерыв: {{ m.dinner_time_start|time:'H:i' }} - {{ m.dinner_time_end|time:'H:i' }}</a></li>
                                {% else %}
                                    <li><a><i class="lnr lnr-dinner"></i> Без обеденного перерыва </a></li>
                            {% endif %}
                            {% if m.phone %}
                                <li><a><i class="lnr lnr-phone"></i> Телеофон: {{ m.phone }} </a></li>
                            {% endif %}
                            <hr>
                        {% endfor %}
{#                        {% for m in promotion_details_not_main %}#}
{#                            {% if m.schedule_start and m.schedule_end %}#}
{#                                <li><a><i class="lnr lnr-home"></i> Адрес: {{ promotion.country }}, {{ promotion.region }}, г. {{ promotion.town }}, {{ m.address }}</a>#}
{#                                <li><a><i class="lnr lnr-clock"></i> Часы работы (Пн - Пт): {{ m.schedule_start|time:'H:i' }} - {{ m.schedule_end|time:'H:i' }}</a></li>#}
{#                                {% else %}#}
{#                                    <li><a><i class="lnr lnr-calendar-full"></i> Часы работы: круглосуточно </a></li>#}
{#                            {% endif %}#}
{#                            {% if m.weekend_start and m.weekend_end %}#}
{#                                <li><a><i class="lnr lnr-clock"></i> Часы работы (Суббота): {{ m.weekend_start|time:'H:i' }} - {{ m.weekend_end|time:'H:i' }}</a></li>#}
{#                                {% else %}#}
{#                                    <li><a><i class="lnr lnr-calendar-full"></i> Суббота - выходной день </a></li>#}
{#                            {% endif %}#}
{#                            {% if m.weekend2_start and m.weekend2_end %}#}
{#                                <li><a><i class="lnr lnr-clock"></i> Часы работы (Воскресенье): {{ m.weekend2_start|time:'H:i' }} - {{ m.weekend2_end|time:'H:i' }}</a></li>#}
{#                                {% else %}#}
{#                                    <li><a><i class="lnr lnr-calendar-full"></i> Воскресенье - выходной день </a></li>#}
{#                            {% endif %}#}
{#                            {% if m.dinner_time_start and m.dinner_time_end %}#}
{#                                <li><a><i class="lnr lnr-dinner"></i> Обеденный перерыв: {{ m.dinner_time_start|time:'H:i' }} - {{ m.dinner_time_end|time:'H:i' }}</a></li>#}
{#                                {% else %}#}
{#                                    <li><a><i class="lnr lnr-dinner"></i> Без обеденного перерыва </a></li>#}
{#                            {% endif %}#}
{#                            {% if m.phone %}#}
{#                                <li><a><i class="lnr lnr-phone"></i> Телеофон: {{ m.phone }} </a></li>#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
                    </ul>
                    <p>{{promotion.description}}</p>
                    {% if promotion.site %}
                        <div class="card_area">
                            <a class="main_btn" target="_blank" href="{{ promotion.site }}">Сайт </a>
                        </div>
                        {% else %}
                        <div class="card_area">
                            <a class="active" href="{% url 'reclame:promotion_list' %}">Назад</a>
                        </div>
                    {% endif %}
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="../../../static/js/jquery-3.2.1.min.js"></script>
<script src="../../../static/js/popper.js"></script>
<script src="../../../static/js/bootstrap.min.js"></script>
<script src="../../../static/js/stellar.js"></script>
<script src="../../../static/vendors/lightbox/simpleLightbox.min.js"></script>
<script src="../../../static/vendors/nice-select/js/jquery.nice-select.min.js"></script>
<script src="../../../static/vendors/isotope/imagesloaded.pkgd.min.js"></script>
<script src="../../../static/vendors/isotope/isotope-min.js"></script>
<script src="../../../static/vendors/owl-carousel/owl.carousel.min.js"></script>
<script src="../../../static/js/jquery.ajaxchimp.min.js"></script>
<script src="../../../static/vendors/counter-up/jquery.waypoints.min.js"></script>
<script src="../../../static/vendors/flipclock/timer.js"></script>
<script src="../../../static/vendors/counter-up/jquery.counterup.js"></script>
<script src="../../../static/js/mail-script.js"></script>
<script src="../../../static/js/theme.js"></script>

{% endblock %}

templates/reclame/pagination.html
<div class="right_page ml-auto">
    <nav class="cat_page" aria-label="Page navigation example">
        <ul class="pagination">
            {% if page.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a></li>
            {% endif %}
            {% for i in page.paginator.page_range %}
                {% if page.number == i %}
                    <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% elif i > page.number|add:'-1' and i < page.number|add:'1' %}
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{#                    <div class="right_page ml-auto">#}
{#                        <nav class="cat_page" aria-label="Page navigation example">#}
{#                            <ul class="pagination">#}
{#                                <li class="page-item"><a class="page-link" href="#"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a></li>#}
{#                                <li class="page-item active"><a class="page-link" href="#">1</a></li>#}
{#                                <li class="page-item"><a class="page-link" href="#">2</a></li>#}
{#                                <li class="page-item"><a class="page-link" href="#">3</a></li>#}
{#                                <li class="page-item blank"><a class="page-link" href="#">...</a></li>#}
{#                                <li class="page-item"><a class="page-link" href="#">6</a></li>#}
{#                                <li class="page-item"><a class="page-link" href="#"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a></li>#}
{#                            </ul>#}
{#                        </nav>#}
{#                    </div>#}