ad/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'ad'

urlpatterns = [
    path('', views.promotion_list, name='promotion_list'),
    path('<slug:category_slug>/', views.promotion_list, name='promotion_list_by_category'),
    path('<slug:subcategory_slug>/', views.promotion_list, name='promotion_list_by_subcategory'),
    path('<int:id>/<slug:slug>/', views.promotion_detail, name='promotion_detail'),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gsp_testing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account_master/', include('account_master.urls')),
    # path('ad/', include('ad.urls', namespace='ad')),
    path('promotions/', include('reclame.urls', namespace='promotions')),
    path('', include('job.urls', namespace='job')),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ad/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название категории')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Nazvanie_kategorii')
    is_active = models.BooleanField(default=True, null=True, blank=True, verbose_name='Активность категории')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория рекламы'
        verbose_name_plural = 'Категории реклам'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('ad:promotion_list_by_category', args=[self.slug])


class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE,
                                 verbose_name='Категория рекламы')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название подкатегории')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Nazvanie_podkategorii')
    is_active = models.BooleanField(default=True, null=True, blank=True, verbose_name='Активность категории')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Подкатегория рекламы'
        verbose_name_plural = 'Подкатегории реклам'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('ad:promotion_list_by_subcategory', args=[self.slug])


class Promotion(models.Model):
    category = models.ManyToManyField(Category, related_name='promotions', blank=True,
                                 verbose_name='Категория рекламы')
    subcategory = models.ForeignKey(SubCategory, related_name='promotions', on_delete=models.CASCADE,
                                    verbose_name='Податегория рекламы')
    # subcategory_2 = models.ManyToManyField(Category, blank=True, null=True, verbose_name='Категория рекламы_2')
    name = models.CharField(blank=True, null=True, default=None, max_length=200, verbose_name='Название рекламодателя')
    slug = models.SlugField(max_length=200, db_index=True, verbose_name='Nazvanie_reklamodatelya')
    country = models.CharField(blank=True, null=True, default='Россия', max_length=200, verbose_name='Страна')
    region = models.CharField(blank=True, null=True, default='Курская область', max_length=200, verbose_name='Регион')
    town = models.CharField(blank=True, null=True, default='Курск', max_length=200, verbose_name='Город')
    address = models.TextField(max_length=512, blank=True, verbose_name='Адрес')
    site = models.URLField(max_length=1024, blank=True, default=None, null=None, verbose_name='Сайт')
    phone = models.CharField(max_length=128, blank=True, null=True, default=None, verbose_name='Номер тел.')
    email = models.EmailField(max_length=128, blank=True, null=True, default=None, verbose_name='Емейл')
    photo = models.ImageField(upload_to='promotions_photos/%Y/%m/%d', blank=True, verbose_name='Фото')
    logotype = models.ImageField(upload_to='promotions_logotypes/%Y/%m/%d', blank=True, verbose_name='Логотип')
    description = models.TextField(max_length=2048, blank=True, verbose_name='Описание деятельности')
    is_active = models.BooleanField(default=False, verbose_name='Активность рекламы')
    paid = models.BooleanField(default=False, verbose_name='Оплачен показ рекламы?')
    schedule_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Пон - Пт)')
    schedule_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Пон - Пт)')
    weekend_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Суббота)')
    weekend_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Суббота)')
    weekend2_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Воскресенье)')
    weekend2_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Воскресенье)')
    dinner_time_start = models.TimeField(blank=True, null=True, verbose_name='Обеденный перерыв (начало)')
    dinner_time_end = models.TimeField(blank=True, null=True, verbose_name='Обеденный перерыв (конец)')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    @property
    def Категории(self):
        return "\n".join([p.name for p in self.category.all()])

    class Meta:
        ordering = ('-created', 'name')
        index_together = (('id', 'slug'),)
        verbose_name = 'Рекламирование'
        verbose_name_plural = 'Рекламирование'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('ad:promotion_detail', args=[self.id, self.slug])


class PromotionDetails(models.Model):
    promotion = models.ForeignKey(Promotion, blank=True, null=True, default=None, on_delete=models.CASCADE, verbose_name='Место под рекламу (детали)')
    is_main = models.BooleanField(default=False, blank=True, null=True, verbose_name='Главный офис')
    is_not_main = models.BooleanField(default=True, blank=True, null=True, verbose_name='Дополнительный офис')
    is_active = models.BooleanField(default=True, blank=True, null=True, verbose_name='Активный?')
    schedule_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Пон - Пт)')
    schedule_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Пон - Пт)')
    weekend_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Суббота)')
    weekend_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Суббота)')
    weekend2_start = models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня (Воскресенье)')
    weekend2_end = models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня (Воскресенье)')
    dinner_time_start = models.TimeField(blank=True, null=True, verbose_name='Обеденный перерыв (начало)')
    dinner_time_end = models.TimeField(blank=True, null=True, verbose_name='Обеденный перерыв (конец)')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Подробная информация к рекламодателям'
        verbose_name_plural = 'Подробная информация к рекламодателям'

ad/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, SubCategory, Promotion
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def promotion_list(request, category_slug=None, subcategory_slug=None):
    category = None
    subcategory = None
    categories = Category.objects.filter(is_active=True)
    subcategories = SubCategory.objects.filter(is_active=True)
    object_list = Promotion.objects.filter(is_active=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        object_list = object_list.filter(category=category)
    if subcategory_slug:
        subcategory = get_object_or_404(SubCategory, slug=subcategory_slug)
        object_list = object_list.filter(subcategory=subcategory)
    paginator = Paginator(object_list, 50)
    page = request.GET.get('page')
    try:
        promotions = paginator.page(page)
    except PageNotAnInteger:
        promotions = paginator.page(1)
    except EmptyPage:
        promotions = paginator.page(paginator.num_pages)

    return render(request, 'ad/list.html', {'category': category,
                                            'categories': categories,
                                            'subcategory': subcategory,
                                            'subcategories': subcategories,
                                            'page': page,
                                            'promotions': promotions})


def promotion_detail(request, id, slug):
    promotion = get_object_or_404(Promotion, id=id, slug=slug, is_active=True)
    return render(request, 'ad/detail.html', {'promotion': promotion})

templates/ad/detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}{{ promotion.name }}{% endblock %}
{% block content %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../../../static/css/bootstrap.css">
    <link rel="stylesheet" href="../../../static/vendors/linericon/style.css">
    <link rel="stylesheet" href="../../../static/css/font-awesome.min.css">
    <link rel="stylesheet" href="../../../static/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="../../../static/vendors/lightbox/simpleLightbox.css">
    <link rel="stylesheet" href="../../../static/vendors/nice-select/css/nice-select.css">
    <link rel="stylesheet" href="../../../static/vendors/animate-css/animate.css">
    <link rel="stylesheet" href="../../../static/vendors/jquery-ui/jquery-ui.css">
    <!-- main css -->
    <link rel="stylesheet" href="../../../static/css/style.css">
    <link rel="stylesheet" href="../../../static/css/responsive.css">

<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>{% if promotion %}{{ promotion.name }}{% else %}Работа{% endif %}</h2>
                <div class="page_link">
                    <a href={% url 'ad:promotion_list' %}>Домой</a>
                    <a href="#">{% if promotion %}{{ promotion.name }}{% else %}Работа{% endif %}</a>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="product_image_area">
    <div class="container">
        <div class="row s_product_inner">
            <div class="col-lg-6">
                <div class="s_product_img">
                    <img class="img-fluid" src="{% if promotion.photo %}{{ promotion.photo.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
{#							<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">#}
{#								<ol class="carousel-indicators">#}
{#									<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active">#}
{#										<img src="img/product/single-product/s-product-s-2.jpg" alt="">#}
{#									</li>#}
{#									<li data-target="#carouselExampleIndicators" data-slide-to="1">#}
{#										<img src="img/product/single-product/s-product-s-3.jpg" alt="">#}
{#									</li>#}
{#									<li data-target="#carouselExampleIndicators" data-slide-to="2">#}
{#										<img src="img/product/single-product/s-product-s-4.jpg" alt="">#}
{#									</li>#}
{#								</ol>#}
{#								<div class="carousel-inner">#}
{#									<div class="carousel-item active">#}
{#										<img class="d-block w-100" src="img/product/single-product/s-product-1.jpg" alt="First slide">#}
{#									</div>#}
{#									<div class="carousel-item">#}
{#										<img class="d-block w-100" src="img/product/single-product/s-product-1.jpg" alt="Second slide">#}
{#									</div>#}
{#									<div class="carousel-item">#}
{#										<img class="d-block w-100" src="img/product/single-product/s-product-1.jpg" alt="Third slide">#}
{#									</div>#}
{#								</div>#}
{#							</div>#}
                </div>
            </div>
            <div class="col-lg-5 offset-lg-1">
                <div class="s_product_text">
                    <h3>{{ promotion.name }}</h3>
                    <ul class="list">
{#                        <li><a class="active" href="{{ promotion.category.get_absolute_url }}">{{ promotion.category }}</a></li>#}
                        <li><a><i class="lnr lnr-home"></i> Адрес: {{ promotion.country }}, {{ promotion.region }}, {{ promotion.town }}, {{ promotion.address }}</a></li>
                        {% if promotion.email %}
                            <li><a><i class="lnr lnr-envelope"></i> E-mail: {{ promotion.email }}</a></li>
                        {% endif %}
                        {% if promotion.schedule_start and promotion.schedule_end %}
                        <li><a><i class="lnr lnr-clock"></i> Часы работы (Пн - Пт): {{ promotion.schedule_start|time:'H:i' }} - {{ promotion.schedule_end|time:'H:i' }}</a></li>
                        {% else %}
                        <li><a><i class="lnr lnr-calendar-full"></i> Часы работы: круглосуточно </a></li>
                        {% endif %}
                        {% if promotion.weekend_start and promotion.weekend_end %}
                        <li><a><i class="lnr lnr-clock"></i> Часы работы (Суббота): {{ promotion.weekend_start|time:'H:i' }} - {{ promotion.weekend_end|time:'H:i' }}</a></li>
                        {% else %}
                        <li><a><i class="lnr lnr-calendar-full"></i> Суббота - выходной день </a></li>
                        {% endif %}
                        {% if promotion.weekend2_start and promotion.weekend2_end %}
                        <li><a><i class="lnr lnr-clock"></i> Часы работы (Воскресенье): {{ promotion.weekend2_start|time:'H:i' }} - {{ promotion.weekend2_end|time:'H:i' }}</a></li>
                        {% else %}
                        <li><a><i class="lnr lnr-calendar-full"></i> Воскресенье - выходной день </a></li>
                        {% endif %}
                        {% if promotion.dinner_time_start and promotion.dinner_time_end %}
                        <li><a><i class="lnr lnr-dinner"></i> Обеденный перерыв: {{ promotion.dinner_time_start|time:'H:i' }} - {{ promotion.dinner_time_end|time:'H:i' }}</a></li>
                        {% else %}
                        <li><a><i class="lnr lnr-dinner"></i> Без обеденного перерыва </a></li>
                        {% endif %}
                        {% if promotion.phone %}
                        <li><a><i class="lnr lnr-phone"></i> Телеофон: {{ promotion.phone }} </a></li>
                        {% endif %}
                    </ul>
                    <p>{{promotion.description}}</p>
                    {% if promotion.site %}
                        <div class="card_area">
                            <a class="main_btn" target="_blank" href="{{ promotion.site }}">Сайт </a>
                        </div>
                        {% else %}
                        <div class="card_area">
                            <a class="active" href="{% url 'ad:promotion_list' %}">Назад</a>
                        </div>
                    {% endif %}
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="../../../static/js/jquery-3.2.1.min.js"></script>
<script src="../../../static/js/popper.js"></script>
<script src="../../../static/js/bootstrap.min.js"></script>
<script src="../../../static/js/stellar.js"></script>
<script src="../../../static/vendors/lightbox/simpleLightbox.min.js"></script>
<script src="../../../static/vendors/nice-select/js/jquery.nice-select.min.js"></script>
<script src="../../../static/vendors/isotope/imagesloaded.pkgd.min.js"></script>
<script src="../../../static/vendors/isotope/isotope-min.js"></script>
<script src="../../../static/vendors/owl-carousel/owl.carousel.min.js"></script>
<script src="../../../static/js/jquery.ajaxchimp.min.js"></script>
<script src="../../../static/vendors/counter-up/jquery.waypoints.min.js"></script>
<script src="../../../static/vendors/flipclock/timer.js"></script>
<script src="../../../static/vendors/counter-up/jquery.counterup.js"></script>
<script src="../../../static/js/mail-script.js"></script>
<script src="../../../static/js/theme.js"></script>

{% endblock %}

templates/ad/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {% if category %}
        {{ category.name }}
        {% else %}Реклама
    {% endif %}
{% endblock %}

{% block content %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="../../static/css/bootstrap.css">
<link rel="stylesheet" href="../../static/vendors/linericon/style.css">
<link rel="stylesheet" href="../../static/css/font-awesome.min.css">
<link rel="stylesheet" href="../../static/vendors/owl-carousel/owl.carousel.min.css">
<link rel="stylesheet" href="../../static/vendors/lightbox/simpleLightbox.css">
<link rel="stylesheet" href="../../static/vendors/nice-select/css/nice-select.css">
<link rel="stylesheet" href="../../static/vendors/animate-css/animate.css">
<link rel="stylesheet" href="../../static/vendors/jquery-ui/jquery-ui.css">
<!-- main css -->
<link rel="stylesheet" href="../../static/css/style.css">
<link rel="stylesheet" href="../../static/css/responsive.css">

<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>{% if category %}{{ category.name }}{% else %}Реклама{% endif %}</h2>
                <div class="page_link">
                    <a href="#">Домой</a>
                    <a href="#">Все категории работ</a>
                    <a href="#">{% if category %}{{ category.name }}{% else %}Реклмаы{% endif %}</a>
                </div>
                <div class="main_add_offer">
        			<a class="main_btn" href="#">Добавить рекламу</a>
        		</div>
            </div>
        </div>
    </div>
</section>

<section class="cat_product_area p_120">
    <div class="container">
        <div class="row flex-row-reverse">
            <div class="col-lg-9">
                <div class="product_top_bar">
                    <div class="left_dorp">
                        <select class="sorting">
                            <option value="1">Сортировать заказы</option>
                            <option value="2">Сортировка по принципу 1</option>
                            <option value="4">Сортировка по принципу 2</option>
                        </select>
{#                        <select class="show">#}
{#                            <option value="1">Показать</option>#}
{#                            <option value="2">Показать 14</option>#}
{#                            <option value="4">Показать 16</option>#}
{#                        </select>#}
                    </div>
                    {% include 'ad/pagination.html' with page=promotions %}
                </div>
                <div class="latest_product_inner row">
{#                    {% for promotion in promotions %}#}
{#                        <div class="col-md-12">#}
{#                            <div class="offer_post">#}
{#                                <div class="offer_details">#}
{#                                    {% if promotion.site %}#}
{#                                    <a href="{{ promotion.site }}" target="_blank"><h2>{{ promotion.name }}</h2></a>#}
{#                                    {% else %}#}
{#                                    <a><h2>{{ promotion.name }}</h2></a>#}
{#                                    {% endif %}#}
{#                                    <p>{{promotion.description|truncatechars:220}}</p>#}
{#                                    <div class="offer_info text-left">#}
{#                                        <div class="offer_tag">#}
{#                                            <a class="active" href="#">{{ promotion.category }}</a>#}
{#                                        </div>#}
{#                                        <ul class="offer_meta list">#}
{#                                            <li><a href="/"><i class="lnr lnr-home"></i> Адрес: {{ promotion.country }}, {{ promotion.region }}, {{ promotion.town }}, {{ promotion.address }}</a></li>#}
{#                                            {% if promotion.schedule_start and promotion.schedule_end %}#}
{#                                            <li><a><i class="lnr lnr-clock"></i> Часы работы: {{ promotion.schedule_start|time:'H:i' }} - {{ promotion.schedule_end|time:'H:i' }}</a></li>#}
{#                                            {% else %}#}
{#                                            <li><a><i class="lnr lnr-calendar-full"></i> Часы работы: круглосуточно </a></li>#}
{#                                            {% endif %}#}
{#                                            {% if promotion.phone %}#}
{#                                            <li><a><i class="lnr lnr-phone"></i> Телеофон: {{ promotion.phone }} </a></li>#}
{#                                            {% endif %}#}
{#                                        </ul>#}
{#                                    </div>#}
{#                                    <a href="{{ promotion.get_absolute_url }}" class="white_bg_btn">Подробнее</a>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    {% endfor %}#}

                    {% for promotion in promotions %}
                        <div class="col-lg-4 col-md-4 col-sm-6">
                            <div class="f_p_item">
                                <div class="f_p_img">
                                    <a href="{{ promotion.get_absolute_url }}">
                                        <img class="img-fluid" src="{% if promotion.logotype %}{{ promotion.logotype.url }}{%else %}{% static "img/no_image.png" %}{% endif %}" alt="">
                                    </a>
{#                                    <div class="p_icon">#}
{#                                        <a href="#"><i class="lnr lnr-checkmark-circle"></i></a>#}
{#                                        <a href="#"><i class="lnr lnr-user"></i></a>#}
{#                                    </div>#}
                                </div>
                                <a href="{{ promotion.get_absolute_url }}">
                                    <h4>{{ promotion.name }}</h4>
                                </a>
                                <a href="{{ promotion.get_absolute_url }}">
                                    <h4>{{ promotion.subcategory }}</h4>
                                </a>
                                <h5>{{ promotion.address }}</h5>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-3">
                <div class="left_sidebar_area">
                    <aside class="left_widgets cat_widgets">
                        <div class="l_w_title">
                            <h3>Все для стройки и ремонта</h3>
                        </div>
                        <div class="widgets_inner">
                            <ul class="list">
                                <li {% if not category %} class="selected" {% endif %}>
                                    <a href="{% url "ad:promotion_list" %}">Все</a>
                                    </li>
                                        {% for c in categories %}
                                            <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                                                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                                            </li>
                                        {% endfor %}
                                    <li>
                                </li>
                            </ul>
                        </div>
                    </aside>
{#                    <aside class="left_widgets p_filter_widgets">#}
{#                        <div class="l_w_title">#}
{#                            <h3>Product Filters</h3>#}
{#                        </div>#}
{#                        <div class="widgets_inner">#}
{#                            <h4>Brand</h4>#}
{#                            <ul class="list">#}
{#                                <li><a href="#">Apple</a></li>#}
{#                                <li><a href="#">Asus</a></li>#}
{#                                <li class="active"><a href="#">Gionee</a></li>#}
{#                                <li><a href="#">Micromax</a></li>#}
{#                                <li><a href="#">Samsung</a></li>#}
{#                            </ul>#}
{#                        </div>#}
{#                        <div class="widgets_inner">#}
{#                            <h4>Color</h4>#}
{#                            <ul class="list">#}
{#                                <li><a href="#">Black</a></li>#}
{#                                <li><a href="#">Black Leather</a></li>#}
{#                                <li class="active"><a href="#">Black with red</a></li>#}
{#                                <li><a href="#">Gold</a></li>#}
{#                                <li><a href="#">Spacegrey</a></li>#}
{#                            </ul>#}
{#                        </div>#}
{#                        <div class="widgets_inner">#}
{#                            <h4>Price</h4>#}
{#                            <div class="range_item">#}
{#                                <div id="slider-range"></div>#}
{#                                <div class="row m0">#}
{#                                    <label for="amount">Price : </label>#}
{#                                    <input type="text" id="amount" readonly>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </aside>#}
                </div>
            </div>
        </div>
    </div>
</section>

{#<!--================Clients Logo Area =================-->#}
{#<section class="clients_logo_area">#}
{#    <div class="container">#}
{#        <div class="main_title">#}
{#            <h2>Лучшие бренды этого месяца</h2>#}
{#            <p>Кто чрезвычайно влюблен в нас <3 </p>#}
{#        </div>#}
{#        <div class="clients_slider owl-carousel">#}
{#            <div class="item">#}
{#                <a href="http://ekas-org.ru/" target="_blank">#}
{#                <img src="../../static/img/clients-logo/c-logo-1.png" alt="">#}
{#                </a>#}
{#            </div>#}
{#            <div class="item">#}
{#                <a href="http://ekas-org.ru/" target="_blank">#}
{#                <img src="../../static/img/clients-logo/c-logo-2.png" alt="">#}
{#                </a>#}
{#            </div>#}
{#            <div class="item">#}
{#                <a href="http://ekas-org.ru/" target="_blank">#}
{#                <img src="../../static/img/clients-logo/c-logo-3.png" alt="">#}
{#                </a>#}
{#            </div>#}
{#            <div class="item">#}
{#                <a href="http://ekas-org.ru/" target="_blank">#}
{#                <img src="../../static/img/clients-logo/logo_kodremonta.png" alt="">#}
{#                </a>#}
{#            </div>#}
{#            <div class="item">#}
{#                <a href="http://ekas-org.ru/" target="_blank">#}
{#                <img src="../../static/img/clients-logo/logo_kodremonta.png" alt="">#}
{#                </a>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</section>#}
{#<!--================End Clients Logo Area =================-->#}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="../../static/js/jquery-3.2.1.min.js"></script>
<script src="../../static/js/popper.js"></script>
<script src="../../static/js/bootstrap.min.js"></script>
<script src="../../static/js/stellar.js"></script>
<script src="../../static/vendors/lightbox/simpleLightbox.min.js"></script>
<script src="../../static/vendors/nice-select/js/jquery.nice-select.min.js"></script>
<script src="../../static/vendors/isotope/imagesloaded.pkgd.min.js"></script>
<script src="../../static/vendors/isotope/isotope-min.js"></script>
<script src="../../static/vendors/owl-carousel/owl.carousel.min.js"></script>
<script src="../../static/js/jquery.ajaxchimp.min.js"></script>
<script src="../../static/vendors/counter-up/jquery.waypoints.min.js"></script>
<script src="../../static/vendors/flipclock/timer.js"></script>
<script src="../../static/vendors/counter-up/jquery.counterup.js"></script>
<script src="../../static/js/mail-script.js"></script>
<script src="../../static/js/theme.js"></script>

{% endblock content %}